### ISSUE TITLE
Cannot reset password 

### ISSUE THREAD

**Issue by saraheagle** [Typesetter/Typesetter#359] opened 2019-12-16 10:18 UTC
The email "New Password" arrives, but the new, randomly generated pw does not work.
The site has just been updated to Typesetter 5.1.
Had the same issue on the older version too.
Thanks

**Comment by juek** [comment] 2019-12-16 19:16
Hi sarah
the problem is already fixed in the upcoming release.

**Comment by saraheagle** [comment] 2019-12-17 07:17
Brilliant, I'll keep my eye out for it. Thanks very much :)

**Comment by gtbu** [comment] 2019-12-19 16:27
If You have no access You can edit  "/data/_site/users.php" and change 'passhash' => 'password_hash' to 'passhash' => 'sha512'  for every user. Then 'renew lost password' should function ( users sholud not use password_hash as security)

**Closed** 2019-12-22 10:08 UTC
