### ISSUE TITLE
Archive.php: call_user_func_array() expects parameter 1 to be a valid callback

### ISSUE THREAD

**Issue by Botster** [Typesetter/Typesetter#314] opened 2019-05-22 23:09 UTC
When trying to download and install a ZIP-archived Plugin using the Admin Panel (ie. remotely), I get a message that extraction failed and the following line in the server error log:

PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /home/user/public_html/typesetter/include/tool/Archive.php on line 153

Line 153 in Archive.php is: return call_user_func_array( array($this->php_object,$name), $arguments);

If the ZipArchive class does not exist, the InitZip function quietly returns without initializing $this->php_object. No warning is given.

I was able to resolve this issue by installing the php7-zip module.

However, it seems that a warning should be given informing that the required module is not installed, and that Zip module should be listed as an Installation Requirement at https://www.typesettercms.com/Docs/Installation.

**Comment by gtbu** [comment] 2019-05-29 10:11
Have You checked in the CMS under tools - > sitecheck that everything is ok.
There can be  2 reasons for this error : 
1. The first is that in Your account the websockets are deactivated. Then this error happens with download of themes and plugins.
2. There can be a transmission error caused by a security scanner of Your provider 
Can You try to install the plugin direct under Plugins by ftp and then put all rights of 
the directories and files under the cms- installation - directory to 755

**Comment by Botster** [comment] 2019-05-29 19:35
> There can be 2 reasons for this error :

Thanks for the comment. However, it is not a download issue. It is an extraction issue which I verified by analyzing and debugging the code.

As I stated, "I was able to resolve this issue by installing the php7-zip module." So, the lack of availability of that ZIP module was the cause of the error.

There is no Site Check under Tools. But Site Status says, "100% of your data files passed the health check. A total of 85 files were checked." Obviously it only checks data files and not for missing PHP modules.

**Comment by gtbu** [comment] 2019-09-03 12:47
It is true that it is better , if a popup with an explaination appears - as i already asked in the forum.
This error may happen if Your provider  has deactivated the sockets (and some time ago when remote loading was disabled by cloudflare)

**Comment by Botster** [comment] 2019-09-04 00:00
Since, again, "I was able to resolve this issue by installing the php7-zip module," it had nothing to do with sockets nor remote loading. Are you actually trying to confuse people?

**Comment by juek** [comment] 2019-11-05 22:51
Installer now checks for [PHP archive support](https://github.com/Typesetter/Typesetter/commit/dd1020e2725102d413f0ec09a4a54d3fe4afec08)

**Closed by juek** 2019-11-05 22:51 UTC
