### ISSUE TITLE
Rectangular Thumbs and Image Captions

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#171] opened 2017-05-16 19:54 UTC
Many TS users wanted to have the opportunity to have rectangular, but not square thumbs. This theme already was discussed on a forum, but without a decision.

I did for itself the patch of ТS  kernel for rectangular thumbs and it works fine. But I would like that this possibility was in original TS.
Juergen, is it possible that You use my patch to do an option in Settings, to let user choose between standard square thumbs and rectangular one? Thumbs recreation link we already have.
Patch is in include1.zip
[include1.zip](https://github.com/Typesetter/Typesetter/files/1005641/include1.zip)

Also I have made patch to automatically add image caption from its file name. It's useful for creation of bulk galleries. It also will be good as option for some users. Can you take it into account for inclusion in the core of the TS?
Patch is in include2.zip
[include2.zip](https://github.com/Typesetter/Typesetter/files/1005664/include2.zip)

**Comment by juek** [comment] 2017-05-16 23:05
Thx mathotilo, I'll look ino it. 

Image alt from filenames is already here -> see [commit](https://github.com/Typesetter/Typesetter/commit/607ad507aac4a3030604b7cf2ebe9598e179d7b6). Did you build upon this version?
I'm currently working on the image gallery with some additional features and responsive styles and will try to merge your patches when I commit.

**Comment by mahotilo** [comment] 2017-05-17 06:14
Thank you!
No, I didn't use your version.
I made only image Caption for gallery to not name it manually.
All patches starts from //==== MOD - 
and have 1-3 lines in one place

**Comment by juek** [comment] 2017-06-17 09:33
With today's [commits (June 17)](https://github.com/Typesetter/Typesetter/commits), we now have optional rectangular thumbs and original image aspect preservation.

**Comment by mahotilo** [comment] 2017-06-17 17:27
Cool news!

I found some problem in new Gallery. 
- Keep Aspect Ratio -> on 
- Gallery theme -> Square tiles
- hover thumb
- see uncovered part in the bottom of thumb 4px height!

With 'Keep Aspect Ratio -> off' all is ok.

**Comment by juek** [comment] 2017-06-17 17:32
> I found some problem in new Gallery

Yep, gallery and new thumb sizes is not yet solved. Will need some rework.

**Comment by mahotilo** [comment] 2017-06-17 17:33
Yeah, I get it.

**Comment by juek** [comment] 2017-06-19 00:25
Latest [commit](https://github.com/Typesetter/Typesetter/commit/d89369634436a8565c3f031d2406784d293373fb) comes with a possible solution for proportional thumbs. Renamed 'Square Tiles' to 'Masonry' (…for now, the style dropdowns will probably become icons in the end)

**Comment by mahotilo** [comment] 2017-06-19 07:05
Thank You,
I have tried it. Looks good. 

Some user experience.
I see vertical scrollbar in gallery section.
In colorbox extended, Mediawiki style looks shifted right.

**Comment by juek** [comment] 2017-06-19 10:23
> I see vertical scrollbar in gallery section.
In colorbox extended, Mediawiki style looks shifted right.

I cannor reproduce the issues. Can you provide screenshots? (can be dropped here)

**Comment by mahotilo** [comment] 2017-06-19 15:11
First. 
Masonry
Large
Thumbs proportion does no matter

![err1](https://user-images.githubusercontent.com/14929385/27291969-78570a3c-551a-11e7-8223-21503a40ba99.png)

**Comment by mahotilo** [comment] 2017-06-19 15:44
Second
I have check, it doesn't appears on clear TS. I see problem on my Bootstrap SCSS based theme. 
As I can see picture is centered, but `#cboxTitle` overlap it. Also I all time see `#cboxLoadingGraphic`.
I did not change `#cboxTitle` and `#cboxCurrent`. On prev dev release of TS all works good. 
Obviously it is my problem. I have many js+css included in my theme, but I can't see where I have made an error.

![err2](https://user-images.githubusercontent.com/14929385/27292568-8a0d3402-551c-11e7-8759-b6c0ca5189d1.png)
![err3](https://user-images.githubusercontent.com/14929385/27293131-304f246e-551e-11e7-9838-6c3e0a231ddc.png)

**Comment by juek** [comment] 2017-06-20 02:51
> Also I see #cboxLoadingGraphic all time.

The loader image visibility is triggered by JS. So it's most likely a JS error, probably caused by one of the  different JS components you are using. 

We should discuss the Colorbox-Extender + MediaWiki style specific stuff in it's own GitHub repository. It's not related to the gallery at all. The issues are probably inherited from your custom theme CSS.

For the gallery scrollbar. I see this myself once in a while. There is an overflow:auto!important; directive in the gallery CSS, with a comment from Josh next to it saying that it's required. I usually override it with 

```
ul.gp_gallery {
  overflow: hidden !important;
}

```
without negative side effects. 
But I have to check why Josh put it there and it it's still needed before I can remove it from the core CSS.

**Comment by mahotilo** [comment] 2017-06-20 06:51
Thank you!

**Comment by juek** [comment] 2017-06-22 05:54
Overflow/scrollbar issue shuld be fixed with [this commit](https://github.com/Typesetter/Typesetter/commit/0623b2b74a2d49475fa87e9d373e6540b4525865)

**Closed by juek** 2017-06-22 05:54 UTC
