### ISSUE TITLE
Typesetter 5.0-rc1

### ISSUE THREAD

**Issue by Knuzen** [Typesetter/Typesetter#117] opened 2016-02-13 07:42 UTC
Hey Josh, don't know where to write my Feedback.
After Start:
1. Notice (8)
Undefined index: HTTP_REFERER
    in: /var/www/web41/html/tbk/ts5/data/_addoncode/n7dpqbt/Catalog_Easy.php
    on line: 167
    Request: /ts5/
    Method: GET - Show Backtrace
2.The "Close-cross" (right corner) is missing (everywhere)
3.Previews (small PICs) from manage section are missing
4. Small Icons on Workmenu (left upper corner) are missing

All your new funktions are a little difficult but understandable,(for me)
but if you try to explain these to a rooky, he will despair.
My advice, install a swichable profimode depend from a user.
In my opinion, the handling should be as intuitive as possible.

Please stay tuned it, I will continue

**Comment by a2exfr** [comment] 2016-02-13 14:54
_1. Notice (8)
Undefined index: HTTP_REFERER
in: /var/www/web41/html/tbk/ts5/data/_addoncode/n7dpqbt/Catalog_Easy.php_

The first issue is about plugin Catalog_Easy not Typesetter. it's a minor notice that is fixed in new version. The new version will be downloadable in a few days, I hope.

**Comment by juek** [comment] 2016-02-13 15:08
Issues 2, 3 and 4 are all connected to Font Awesome, an icon font now used for most User Interface symbols. 
Do you see some cryptic boxes with small numbers in it or is there simply nothing where the icons should be?
Two questions arise here: Which browser/version are you using and do you have activated loading Font Awesome from CDN (cloudflare) in Settings->CDN?

**Comment by Knuzen** [comment] 2016-02-13 18:26
a2exfr: OK I understand that. I'll wait.

juek: I see nothing, no symbols, and I use OPERA 35.0 , WIN 10 Pro (64bit)
CDN Cloudflare: all is activated, I'm to stupid to understand that sence, pls be patiently

**Comment by juek** [comment] 2016-02-13 19:06
unfortunately I don't have yet any Windows 10 installations running for testing. Under Windows 7 Opera 35 is just fine. Maybe someone with Win 10 may want to pitch in and try to replicate te issue...

@Knuzen: You could check if the same problem occurs in different browsers, e.g. Edge? So we could find out if the problem is system related (unlikely). You could also try to open [http://fortawesome.github.io/Font-Awesome/cheatsheet/](url) and look if Font Awesome Icons are displaying here.

**Comment by Knuzen** [comment] 2016-02-15 18:50
Some problems are solved, since a very new upload. Don't know why.
Every browsers are working well.
No plugins better installed, I'm testing very carefully again.
Thanks for all.

**Comment by juek** [comment] 2016-02-18 00:19
The Hamburger Menu issue is already fixed in current master.
What do you exactly mean with "switch section"? If you wat to re-order them you can drag'n'drop them in the "Page" view of the editor panel.

**Comment by Knuzen** [comment] 2016-02-19 17:09
Sorry, it's a little difficult for me as a german, to switch to the correct english terms
![editmenu](https://cloud.githubusercontent.com/assets/10711934/13182473/378abd58-d732-11e5-9df9-ddb413fbe485.jpg)
This menu I mean, it's static now and this disturbs when editing.

Furthermore, I think the pure insert of one Picture, is not responsiv in the end,
only Picture with text it works fine. 

One request to you,  juek:
Maybe you can help me please, with a responsiv Picture-banner above the typesetter-cms-menu, because I'm not so good to arrange templates. Have you a hint for me?

**Comment by juek** [comment] 2016-02-19 18:14
@Knuzen: 

> One request to you, juek: Maybe you can help me please, with a responsiv Picture-banner above the typesetter-cms-menu, because I'm not so good to arrange templates. Have you a hint for me?

Proabably yes. But it's off-topic here (not related to the core CMS) so we should better discuss it in the [typesetter forum.](http://www.typesettercms.com/Forum?show=f13)

**Closed** 2016-03-07 05:33 UTC
